### ISSUE TITLE
Mean centering causing problems.

### ISSUE THREAD

**Issue by kwagstyl** [rmarkello/pyls#53]
Hi @rmarkello 

I think there's a bug in the mean centering.
If data is inputted as pandas dataframe:
--> 381         X -= X.mean(axis=0, keepdims=True)
    382         Y_agg -= Y_agg.mean(axis=0, keepdims=True)
ValueError: the 'keepdims' parameter is not supported in the pandas implementation of mean()

If data is a numpy array:
ValueError: array must not contain infs or NaNs
and the input data['X'] is filled with NaNs.

**Comment by rmarkello** [comment]
Thanks for the bug report, @kwagstyl !

The numpy bit is expected&mdash;there's no solution for missing data built into `pyls` yet. But the pandas issue is one that should be quick to sort out! I'll fix it as soon as I'm in the office.

Re the missing data: is this the case where you have an entire missing row of data, or where just a few cells are empty? Let me know; if it's the former I can try and come up with a patch quickly.

**Comment by kwagstyl** [comment]
@rmarkello 
Gotcha. Not a problem to have them as numpy arrays.
It's the X (gene) data where there are entire ROIs with no data.
Just double checking how Petra settled on handling these cases.

Konrad

**Comment by rmarkello** [comment]
Alright, the `pandas` issue should be fixed with #54. 

I'll work on the missing data issue next&mdash;I think we decided that we would allow entire rows with missing data and remove them before generating the cross-covariance matrix each time. A different row will be removed from the `Y` matrix during the permutations, but this should (hopefully) be okay. I've opened #55 to handle this!

**Comment by rmarkello** [comment]
Hey @kwagstyl ! I think this should all be fixed now with the merging of #55 🤞 

Would you mind pulling the updated master branch and giving it a try? Providing a pandas DataFrame with a row (or several rows) of missing data should work (n.b., having any missing data that ISN'T an entire row *won't* work). Let me know how it goes!

**Comment by kwagstyl** [comment]
Hi @rmarkello,
Fantastic, that now works.
FYI I needed a minor tweak to lose the first column, which is the ROI index
i.e.
pls_dataset['X']= pd.DataFrame(gene_exp['parcelExpression'][:,1:],
columns=gene_names[1:])

But otherwise I think that's all working!
Thanks!
K
